Repository Astrabit-ST/Luminol, pull requests merged in 2024-01, with the labels that each got.

#83 Use color-eyre for error handling and add a log window
  Cargo.lock
  Cargo.toml
  crates/audio/Cargo.toml
  crates/audio/src/error.rs
  crates/components/Cargo.toml
  crates/components/src/filesystem_view.rs
  crates/components/src/map_view.rs
  crates/components/src/sound_tab.rs
  crates/components/src/tilepicker.rs
  crates/config/Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/data_cache.rs
  crates/core/src/lib.rs
  crates/core/src/project_manager.rs
  crates/core/src/toasts.rs
  crates/data/Cargo.toml
  crates/filesystem/Cargo.toml
  crates/filesystem/src/archiver/file.rs
  crates/filesystem/src/archiver/filesystem.rs
  crates/filesystem/src/archiver/filesystem/impls.rs
  crates/filesystem/src/archiver/filesystem/mod.rs
  crates/filesystem/src/egui_bytes_loader.rs
  crates/filesystem/src/lib.rs
  crates/filesystem/src/list.rs
  crates/filesystem/src/native.rs
  crates/filesystem/src/path_cache.rs
  crates/filesystem/src/project.rs
  crates/filesystem/src/web/events.rs
  crates/filesystem/src/web/mod.rs
  crates/filesystem/src/web/util.rs
  crates/graphics/Cargo.toml
  crates/graphics/src/atlas_loader.rs
  crates/graphics/src/event.rs
  crates/graphics/src/map.rs
  crates/graphics/src/texture_loader.rs
  crates/graphics/src/tiles/atlas.rs
  crates/term/Cargo.toml
  crates/term/src/_impl/mod.rs
  crates/ui/Cargo.toml
  crates/ui/src/tabs/map/mod.rs
  crates/ui/src/windows/archive_manager.rs
  crates/ui/src/windows/console.rs
  crates/ui/src/windows/map_picker.rs
  crates/ui/src/windows/new_project.rs
  crates/web/Cargo.toml
  src/app/log_window.rs
  src/app/mod.rs
  src/app/top_bar.rs
  src/main.rs
Labels: enhancement, code style

#84 Use fragile to remove Send + Sync impls
  Cargo.lock
  Cargo.toml
  crates/components/Cargo.toml
  crates/components/src/tilepicker.rs
  crates/graphics/Cargo.toml
  crates/graphics/src/event.rs
  crates/graphics/src/map.rs
Labels: code style, webassembly

#86 Item editor fixup
  Cargo.lock
  crates/components/Cargo.toml
  crates/components/src/id_vec.rs
  crates/components/src/lib.rs
  crates/core/src/toasts.rs
  crates/data/src/rmxp/item.rs
  crates/filesystem/src/trie.rs
  crates/ui/src/windows/items.rs
  src/app/top_bar.rs
Labels: core functionality

#91 Fix id_vec IDs not being incremented during serialization
  crates/data/src/helpers/id_vec.rs
Labels: bugfix

#90 Lazy path cache
  crates/filesystem/Cargo.toml
  crates/filesystem/src/path_cache.rs
Labels: enhancement

#97 Fix path cache using wrong path separator on Windows
  crates/filesystem/src/path_cache.rs
  crates/filesystem/src/trie.rs
Labels: bugfix

#93 Add layout helper functions
  crates/components/src/filesystem_view.rs
  crates/components/src/id_vec.rs
  crates/components/src/lib.rs
  crates/components/src/ui_ext.rs
  crates/ui/src/windows/archive_manager.rs
  crates/ui/src/windows/items.rs
Labels: code style

#96 Per-project UI persistence
  crates/components/src/map_view.rs
  crates/components/src/sound_tab.rs
  crates/config/src/project.rs
  crates/filesystem/src/project.rs
  crates/ui/src/tabs/map/mod.rs
  crates/ui/src/windows/items.rs
  crates/ui/src/windows/map_picker.rs
  crates/ui/src/windows/script_edit.rs
Labels: enhancement

#88 Update egui to 0.25, wgpu to 0.19 and fix Firefox compatibility
  .github/workflows/build.yml
  Cargo.lock
  Cargo.toml
  assets/compat-test.js
  assets/main.js
  assets/webgpu-test-worker.js
  assets/worker.js
  crates/components/src/ui_ext.rs
  crates/core/Cargo.toml
  crates/eframe/CHANGELOG.md
  crates/eframe/Cargo.toml
  crates/eframe/README.md
  crates/eframe/src/epi.rs
  crates/eframe/src/lib.rs
  crates/eframe/src/native/epi_integration.rs
  crates/eframe/src/native/glow_integration.rs
  crates/eframe/src/native/run.rs
  crates/eframe/src/native/wgpu_integration.rs
  crates/eframe/src/native/winit_integration.rs
  crates/eframe/src/web/app_runner.rs
  crates/eframe/src/web/events.rs
  crates/eframe/src/web/input.rs
  crates/eframe/src/web/mod.rs
  crates/eframe/src/web/text_agent.rs
  crates/eframe/src/web/web_logger.rs
  crates/eframe/src/web/web_painter_glow.rs
  crates/eframe/src/web/web_painter_wgpu.rs
  crates/eframe/src/web/web_runner.rs
  crates/egui-wgpu/CHANGELOG.md
  crates/egui-wgpu/Cargo.toml
  crates/egui-wgpu/README.md
  crates/egui-wgpu/src/lib.rs
  crates/egui-wgpu/src/renderer.rs
  crates/egui-wgpu/src/winit.rs
  crates/filesystem/src/lib.rs
  crates/filesystem/src/web/events.rs
  crates/filesystem/src/web/mod.rs
  crates/graphics/Cargo.toml
  crates/graphics/src/lib.rs
  crates/graphics/src/texture_loader.rs
  crates/term/src/_impl/mod.rs
  crates/ui/Cargo.toml
  crates/web/js/bindings.js
  crates/web/src/bindings.rs
  index.html
  src/main.rs
Labels: dependencies, webassembly
